### PR TITLE
Set compileSdkVersion to 18 (and make corresponding fixes)

### LINKED ISSUE #42: Android tracer crashes jellybean
Here's the stack trace:

```
java.lang.NoClassDefFoundError: java.util.concurrent.ThreadLocalRandom
                                                     at com.lightstep.tracer.shared.AbstractTracer.generateGUID(AbstractTracer.java:587)
                                                     at com.lightstep.tracer.shared.AbstractTracer.<init>(AbstractTracer.java:151)
                                                     at com.lightstep.tracer.android.Tracer.<init>(Tracer.java:31)
```

Note that this class does not exist on Jellybean.

Even more concerning: there are standard lint checks that are supposed to catch this problem but it looks like the gradle config has linting errors turned off (https://github.com/lightstep/lightstep-tracer-java/blob/master/lightstep-tracer-android/build.gradle#L64)

### PR DESCRIPTION
**Pull request by bcronin**
## Summary

Fixes #42 but removing usage of APIs not available in Android SDK 18. The library was causing crashes on JellyBean due to such calls.

* Replaces `ThreadLocalRandom` with an equivalent directly using `ThreadLocal` and `Random`
* Adds a unit test to make sure the equivalent class behaves reasonably :)
* Changes the build settings so `compileSdkVersion` is now 18
* A couple other minor language-level changes to handle the lower `compileSdkVersion`
* Removes the disabled `lintOptions` that were added in very early development (and should have been removed some time ago)

### CODE REVIEW

File: common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java [hunk 1]
```diff
@@ -582,9 +582,27 @@ void addSpan(SpanRecord span) {
...
+   *
+   * See http://stackoverflow.com/questions/2546078/java-random-long-number-in-0-x-n-range
+   */
+  private static ThreadLocal<Random> random = new ThreadLocal<Random>() {
+      @Override
+      protected Random initialValue() {
+        // It'd be nice to get the process ID into the mix, but there's no clear
+        // cross-platform, Java 6-compatible way to determine that
+        return new Random(
+          System.currentTimeMillis() *
```
Comment (bensigelman) [inline common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java]: seems like a great time to use `nanoTime`, though maybe that's not available in Android??

File: lightstep-tracer-jre/src/test/java/com/lightstep/tracer/RuntimeTest.java [hunk 2]
```diff
@@ -64,6 +65,45 @@ public void tracerOptionsAreSupported() {
         JRETracer tracer = new JRETracer(options);
     }
 
+    /**
+     * Note: this test *can* generate a false-positive, but the probability is
+     * so low (the probability of a collision of 8k values in a 2^64 range) that
```
Comment (bensigelman) [inline lightstep-tracer-jre/src/test/java/com/lightstep/tracer/RuntimeTest.java]: 🎂 🎂 🎂

**Comment by bensigelman** [comment]
Thanks -- LGTM!
